recommended_condition_schema:
  BackgroundSuppressionNumberPulses:
    BackgroundSuppression:
      True
  BackgroundSuppressionPulseTime:
    BackgroundSuppression:
      True
  LabelingLocationDescription: "all"
  VascularCrushing: "all"
  VascularCrushingVENC:
    VascularCrushing:
      True
  PCASLType:
    ArterialSpinLabelingType:
      "PCASL"
  CASLType:
    ArterialSpinLabelingType:
      "CASL"
  LabelingDistance: "all"
  LabelingPulseAverageGradient:
    ArterialSpinLabelingType:
      ["PCASL"]
  LabelingPulseMaximumGradient:
    ArterialSpinLabelingType:
      ["PCASL"]
  LabelingPulseAverageB1:
    ArterialSpinLabelingType:
      ["PCASL"]
  LabelingPulseFlipAngle:
    ArterialSpinLabelingType:
      ["PCASL"]
  LabelingPulseInterval:
    ArterialSpinLabelingType:
      ["PCASL"]
  LabelingPulseDuration:
    ArterialSpinLabelingType:
      ["PCASL"]
  PASLType:
    ArterialSpinLabelingType:
      "PASL"
  LabelingSlabThickness:
    ArterialSpinLabelingType:
      "PASL"
  AcquisitionDuration: "all"